### PR TITLE
add plain text support

### PR DESCRIPTION
**Pull request by nybble73**

### CODE REVIEW

**Comment by coderhaoxin** [comment]
:+1:

**Comment by dead-horse** [comment]
https://github.com/koajs/bodyparser#options strict mode should disable plain text support, we must make sure `this.request.body` always be an object in strict mode.

**Comment by nybble73** [comment]
I'm not sure what you mean @dead-horse? strict-mode seems to be scoped to the JSON parser - it shouldn't be affected by this, since this comes into affect by content-type: text/plain.

**Comment by dead-horse** [comment]
We want to make sure when people get request body from `this.request.body` will always get an object in strict mode. so maybe we should change the readme either.

**Comment by nybble73** [comment]
I'm still unclear exactly what you expect the output to be. I believe this comes from this piece of README from co-body:

> strict when set to true, JSON parser will only accept arrays and objects; when false will accept anything JSON.parse accepts. Defaults to true. (also strict mode will always return object).

However, bodyparser delegates all this to co.parse - so we have the exact behaviour that co-body provides. Also co-body does not have any tests for "strict" in anything beside JSON nor documentation for what to expect in a plain text body that would not be plain text but an object instead.

**Comment by tunnckoCore** [comment]
> @nybble73: I'm still unclear

Same here.

@dead-horse it's normal if user send text/plain body to receive string response in the `this.body` and `this.request.body`. Review the [tests dir](https://github.com/tunnckoCore/koa-better-body/blob/refactor/test) in the refactor branch of `koa-better-body`.

Strict mode here, for me is just related to the that the json should be strictly array or object. I called it `jsonStrict` in the refactor of `koa-better-body`. And separately I have more general `strict` mode, for IETF for get, head and delete request, which make more sense.

**Pull request closed without merging**
