### PR TITLE
Add support for Koa 2.x

### PR DESCRIPTION
**Pull request by simplyianm**
Use promises rather than generators to support the new Koa flow.

### CODE REVIEW

**Comment by fengmk2** [comment]
I'm OK to this change. +1
But now we need to maintain two LTS branches 2.x and 3.x.

Need one +1 @dead-horse

**Comment by tejasmanohar** [comment]
As per branching off v2.x, agreed- just like has been done in [koa-route](https://github.com/koajs/route/tree/v2.x) and [koa](https://github.com/koajs/koa/tree/v1.x) itself.

**Comment by dead-horse** [comment]
SGTM

**Comment by dead-horse** [comment]
3.0.0 released

**Comment by tejasmanohar** [comment]
:smile:

**Comment by simplyianm** [comment]
Great! Do you think y'all could check [https://github.com/koajs/logger/pull/34] as well? Thanks!

**Comment by tejasmanohar** [comment]
@simplyianm I got that one :)

**Pull request merged**
