### PR TITLE
feat: support enableTypes and text

### LINKED ISSUE #43: Raw data?
Is there any easy way to get to the raw request body. Or is adding such a feature a possibility?

### PR DESCRIPTION
**Pull request by dead-horse**
closes #43

### CODE REVIEW

**Comment by fengmk2** [comment]
+1

**Comment by fengmk2** [comment]
+1

**Comment by fengmk2** [comment]
I'm not in the npm owner list, please publish a minor version.

**Comment by dead-horse** [comment]
2.2.0

npm owner added

**Comment by i5ting** [comment]
please sync it to `next` branch for koa2 support

**Pull request merged**
